# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyoda < Formula
  desc "Lightweight Go EDBMS — digital twin of the Cyoda platform"
  homepage "https://github.com/cyoda/cyoda-go"
  version "0.7.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.7.4/cyoda_0.7.4_darwin_amd64.tar.gz"
      sha256 "5fd4444aa7e1e031ff92c15cc65102707f3090a3a565b45604211d0d01c6df8a"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.7.4/cyoda_0.7.4_darwin_arm64.tar.gz"
      sha256 "aa191fd3f0933ac444933e2da03447cc360ce12ffbcd8d5168e34c7681d80f29"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.7.4/cyoda_0.7.4_linux_amd64.tar.gz"
      sha256 "63e39730936f61699c880f89c29b6ef39f01ab77ce64e2d4d2bb90240cbe39a8"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.7.4/cyoda_0.7.4_linux_arm64.tar.gz"
      sha256 "18483b3f78568e1cf6341a3d34cdd807cb73c725197c0430b62d20c84dc5a51d"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  def caveats
    <<~EOS
      ==============================================================
      cyoda is installed but not yet initialised. Run:

        cyoda init

      to write the default sqlite configuration to
      #{Dir.home}/.config/cyoda/ with data stored in
      #{Dir.home}/.local/share/cyoda/cyoda.db.

      Alternatively, set CYODA_STORAGE_BACKEND and related env vars
      in your shell environment to run without an on-disk config.
      ==============================================================
    EOS
  end

  test do
    system bin/"cyoda", "--help"
  end
end
