# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyoda < Formula
  desc "Lightweight Go EDBMS — digital twin of the Cyoda platform"
  homepage "https://github.com/cyoda/cyoda-go"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.8.1/cyoda_0.8.1_darwin_amd64.tar.gz"
      sha256 "4a4189eac6ef4ba3bca85244b937b21a1ba2c1785b5e68057e4aa2198d394237"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.8.1/cyoda_0.8.1_darwin_arm64.tar.gz"
      sha256 "2f2caeae5f8ecaf1b8da3da6d2b9ca89fee65ae18d483ffbc9c21eca85df8e54"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.8.1/cyoda_0.8.1_linux_amd64.tar.gz"
      sha256 "d19880a3d62c0cfe3fd443abcbda793ad6d8bfbc7b5dc09e1e819ccae766735f"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda/cyoda-go/releases/download/v0.8.1/cyoda_0.8.1_linux_arm64.tar.gz"
      sha256 "7e954d167cd8f72d65f47b894579c6ca5abda1b35a43bbe57d2c41995d68f901"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  def caveats
    <<~EOS
      ==============================================================
      cyoda is installed but not yet initialised. Run:

        cyoda init

      to write the default sqlite configuration to
      #{Dir.home}/.config/cyoda/ with data stored in
      #{Dir.home}/.local/share/cyoda/cyoda.db.

      Alternatively, set CYODA_STORAGE_BACKEND and related env vars
      in your shell environment to run without an on-disk config.
      ==============================================================
    EOS
  end

  test do
    system bin/"cyoda", "--help"
  end
end
