# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyoda < Formula
  desc "Lightweight Go EDBMS — digital twin of the Cyoda platform"
  homepage "https://github.com/cyoda-platform/cyoda-go"
  version "0.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.7.1/cyoda_0.7.1_darwin_amd64.tar.gz"
      sha256 "4e97a995342f91901a55504ebce4bb98a54e0c2e2fb55bd14b7111cc4213eee4"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.7.1/cyoda_0.7.1_darwin_arm64.tar.gz"
      sha256 "51b5e740ba6ebf1750db1c0ea6829115cb12f3b5963632025eaa3f09e674c346"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.7.1/cyoda_0.7.1_linux_amd64.tar.gz"
      sha256 "d7a3a5c2d46561e196c3d378221eff2cd2f9e8498a398eb31eb44470d4b47c4a"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.7.1/cyoda_0.7.1_linux_arm64.tar.gz"
      sha256 "d6ec627d7b91dffaf18db44ac14201299b0b89dc5ece952dd98edf75a5f3258f"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  def caveats
    <<~EOS
      ==============================================================
      cyoda is installed but not yet initialised. Run:

        cyoda init

      to write the default sqlite configuration to
      #{Dir.home}/.config/cyoda/ with data stored in
      #{Dir.home}/.local/share/cyoda/cyoda.db.

      Alternatively, set CYODA_STORAGE_BACKEND and related env vars
      in your shell environment to run without an on-disk config.
      ==============================================================
    EOS
  end

  test do
    system bin/"cyoda", "--help"
  end
end
